theme = "catppuccin-frappe"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
color-modes = true
completion-replace = true
auto-completion = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false
display-messages = false

[editor.file-picker]
hidden = true
git-ignore = false

[keys.normal]
"G" = "goto_last_line"
"," = "repeat_last_motion"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.g]
"s" = "goto_line_start"
"e" = "goto_line_end"

[keys.normal.space]
"p" = "goto_last_accessed_file"
